-- recovery: orphan rows whose parent product no longer exists
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('11','13','Blue',NULL,'prince-1_667dc3ea.jpg',NULL,NULL,'1','1','2026-08-05 08:52:29');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('15','15','Olive Silk','1000','test-1_bdcbeb9f.jpg','77.00','54.00','1','1','2026-08-06 18:32:15');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('16','22','Rose Petal','QA-ACC-005-ROS','qa-colour-rose.jpg',NULL,NULL,'1','1','2026-08-09 12:52:03');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('17','22','Champagne','QA-ACC-005-CHM','qa-colour-champagne.jpg','949.00','1349.00','2','1','2026-08-09 12:52:03');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('18','22','Midnight Black','QA-ACC-005-BLK','qa-colour-black.jpg',NULL,NULL,'3','1','2026-08-09 12:52:03');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('19','23','Midnight Black','QA-BOT-006-BLK','qa-colour-black.jpg',NULL,NULL,'1','1','2026-08-09 12:52:03');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('20','23','Maroon','QA-BOT-006-MAR','qa-colour-maroon.jpg','1599.00','2099.00','2','1','2026-08-09 12:52:04');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('21','24','Indigo Blue','QA-MSH-007-IND','qa-colour-indigo.jpg',NULL,NULL,'1','1','2026-08-09 12:52:04');
INSERT INTO `product_colors` (`id`,`product_id`,`color_name`,`sku`,`thumbnail`,`price_override`,`mrp_price_override`,`sort_order`,`is_active`,`created_at`) VALUES ('22','24','Bone Ivory','QA-MSH-007-IVR','qa-colour-white.jpg',NULL,NULL,'2','1','2026-08-09 12:52:04');
