-- ZZ TEST menswear/admin test data
INSERT INTO `products` (`id`,`name`,`description`,`price`,`category`,`category_id`,`emoji`,`color`,`badge`,`available`,`image`,`created_at`,`nuts_allergy`,`track_stock`,`stock_qty`,`damage_stock`,`sold_offline`,`total_stock`,`sold_online`,`brand`,`fabric`,`sleeve`,`neck`,`pattern`,`occasion`,`discount_percentage`,`video_url`,`wash_care`,`shipping_info`,`returns_info`,`specifications`,`atelier_code`,`color_way`,`sourcing`,`composition`,`sku`,`barcode`,`weight`,`dimensions`,`tags`,`seo_url`,`meta_title`,`meta_description`,`related_ids`,`cost_price`,`mrp_price`,`hsn_code`,`gst_rate`,`is_deleted`,`fit_description`,`model_height`,`model_size_worn`,`updated_at`,`image_alt`,`use_category_tax`,`price_includes_gst`) VALUES ('47','ZZ TEST Mens Linen Shirt','Temporary menswear test product. Safe to delete.','1200.00','Shirts','17','👔','Bone Ivory','','1','','2026-08-11 05:23:22','0','1','0','0','0','30','0','ZZ TEST Atelier','Linen','Full Sleeve','Collar','Solid','Casual','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00','1800.00','6205','5.00','0',NULL,NULL,NULL,'2026-08-11 05:33:24',NULL,'1','1');
INSERT INTO `products` (`id`,`name`,`description`,`price`,`category`,`category_id`,`emoji`,`color`,`badge`,`available`,`image`,`created_at`,`nuts_allergy`,`track_stock`,`stock_qty`,`damage_stock`,`sold_offline`,`total_stock`,`sold_online`,`brand`,`fabric`,`sleeve`,`neck`,`pattern`,`occasion`,`discount_percentage`,`video_url`,`wash_care`,`shipping_info`,`returns_info`,`specifications`,`atelier_code`,`color_way`,`sourcing`,`composition`,`sku`,`barcode`,`weight`,`dimensions`,`tags`,`seo_url`,`meta_title`,`meta_description`,`related_ids`,`cost_price`,`mrp_price`,`hsn_code`,`gst_rate`,`is_deleted`,`fit_description`,`model_height`,`model_size_worn`,`updated_at`,`image_alt`,`use_category_tax`,`price_includes_gst`) VALUES ('48','ZZ TEST Mens Cotton Kurta','Temporary menswear test product. Safe to delete.','1500.00','Shirts','17','👔','ZZ Test Saffron','','1','','2026-08-11 05:23:22','0','1','0','0','0','30','0','Dievon','Cotton','Full Sleeve','Round Neck','Embroidered','Wedding','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00','2200.00','6205','5.00','0',NULL,NULL,NULL,'2026-08-11 05:34:43',NULL,'1','1');
INSERT INTO `products` (`id`,`name`,`description`,`price`,`category`,`category_id`,`emoji`,`color`,`badge`,`available`,`image`,`created_at`,`nuts_allergy`,`track_stock`,`stock_qty`,`damage_stock`,`sold_offline`,`total_stock`,`sold_online`,`brand`,`fabric`,`sleeve`,`neck`,`pattern`,`occasion`,`discount_percentage`,`video_url`,`wash_care`,`shipping_info`,`returns_info`,`specifications`,`atelier_code`,`color_way`,`sourcing`,`composition`,`sku`,`barcode`,`weight`,`dimensions`,`tags`,`seo_url`,`meta_title`,`meta_description`,`related_ids`,`cost_price`,`mrp_price`,`hsn_code`,`gst_rate`,`is_deleted`,`fit_description`,`model_height`,`model_size_worn`,`updated_at`,`image_alt`,`use_category_tax`,`price_includes_gst`) VALUES ('49','ZZ TEST Mens Formal Trouser','Temporary menswear test product. Safe to delete.','1400.00','Trousers','18','👔','Midnight Black','','1','','2026-08-11 05:23:22','0','1','0','0','0','30','0','Dievon','Cotton','Full Sleeve','Collar','Solid','Formal','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00','1900.00','6205','5.00','0',NULL,NULL,NULL,'2026-08-11 05:23:22',NULL,'1','1');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('139','47','Size: M','1200.00','1','1','2026-08-11 05:23:22',NULL,NULL,'10');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('140','47','Size: L','1200.00','2','1','2026-08-11 05:23:22',NULL,NULL,'12');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('141','47','Size: XL','1200.00','3','1','2026-08-11 05:23:22',NULL,NULL,'8');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('142','48','Size: M','1500.00','1','1','2026-08-11 05:23:22',NULL,NULL,'10');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('143','48','Size: L','1500.00','2','1','2026-08-11 05:23:22',NULL,NULL,'12');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('144','48','Size: XL','1500.00','3','1','2026-08-11 05:23:22',NULL,NULL,'8');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('145','49','Size: M','1400.00','1','1','2026-08-11 05:23:22',NULL,NULL,'10');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('146','49','Size: L','1400.00','2','1','2026-08-11 05:23:22',NULL,NULL,'12');
INSERT INTO `product_variants` (`id`,`product_id`,`name`,`price`,`sort_order`,`available`,`created_at`,`color_id`,`size_code`,`stock_qty`) VALUES ('147','49','Size: XL','1400.00','3','1','2026-08-11 05:23:22',NULL,NULL,'8');
INSERT INTO `brands` (`id`,`name`,`logo`,`status`,`created_at`) VALUES ('7','ZZ TEST Atelier',NULL,'Active','2026-08-11 05:30:41');
INSERT INTO `product_attributes` (`id`,`attr_type`,`name`,`code`,`created_at`) VALUES ('25','color','ZZ Test Saffron','#f4a300','2026-08-11 05:34:10');
INSERT INTO `banners` (`id`,`title`,`subtitle`,`image`,`link`,`status`,`sort_order`,`gender`,`placement`) VALUES ('16','ZZ TEST Menswear Banner','Shirts, trousers and tailoring','silk_3_piece_1784414705496.jpg','shop?for=men','Active','0','men','hero');
